site_name: ShopGuard Chatbot Wiki
site_description: Documentation for Bluelm Shopguard Chatbot
site_author: Bluelm Shopguard Team
copyright: Copyright &copy; 2025 Bluelm Shopguard Team

# Repository
repo_name: shopguard-chatbot
repo_url: https://github.com/bluelm-shopguard/shopguard-chatbot
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # Navigation structure


nav:
  - Home: index.md
  - Wiki: shopguard-chatbot_wiki.md

plugins:
  - search
  - minify:
      minify_html: true
